Frontend
slacgismo/SCRIPT pull request #12
Opened 2019-10-09 20:32 UTC by wyq730

### Why:
* We need an overview page to show the overall map, and a algorithm running page to visualize the result.

### What:
* Finished basic UI of overview page & algorithm running page.

2019-10-09 21:08 UTC, hooshooo requested changes
I think it would be better if it's merged into a non-master branch, such as develop.
As I said, I know little about react, so the only thing I can do is to check the format.
And could you please write some documentations about how to setup the environment or the structure of your code.

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/About/About.js
> +export default About;
Please end up with a new line.
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Algorithms/Algorithm1.js
> +export default Algorithm1;
same here

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Algorithms/Algorithm2.js
> +export default Algorithm2;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Algorithms/Algorithm3.js
> +export default Algorithm3;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Algorithms/Algorithm4.js
> +export default Algorithm4;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Algorithms/Algorithm5.js
> +export default Algorithm5;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Overview/Overview.js
> +export default Overview;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/OverviewMap/OverviewMap.js
> +export default OverviewMap;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/OverviewMap/overviewMapStyled.js
> +}
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/OverviewMap/sampleCounties.js
> +};
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/OverviewMap/sampleCounties.js
> +  }
I think this is only for our demo, so I prefer not merging this into master branch.

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/ResultChart/ResultChart.css
> +}
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/ResultChart/ResultChart.js
> +export default ResultChart;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/ResultChart/ResultChart.js
> +      {x: 1, y: 8},
I think you suppose to get these data through a API call?

2019-10-09 21:08 UTC, hooshooo commented on frontend/store.json
> +}
Is it something related to our project?

2019-10-09 21:08 UTC, hooshooo commented on frontend/package.json
> +  "name": "writers-blog",
I think we can change the name to something like `script-ui`?

2019-10-09 21:08 UTC, hooshooo commented on frontend/.gitignore
> +package-lock.json
Seems it's not ignored in your commits.

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/ResultChart/ResultCharts.js
> +export default ResultCharts;
same

2019-10-09 21:08 UTC, hooshooo commented on frontend/src/Components/Upload/Upload.js
> +export default Upload;
same

2019-10-09 21:08 UTC, proverbs commented on frontend/src/Components/Algorithms/Algorithm4.js
> +        <br/><Content text={'Results'}/>        </div>
I know little about react, but I think we are supposed to format the embedded html code as well.

2019-12-03 23:23 UTC, wyq730 commented
Replaced by #54

2019-12-03 23:23 UTC, closed without merging